name: Publish

on:
  push:
    tags:
      - "v*"
      # - "[0-9]+.[0-9]+.[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      # - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest

    environment:
      name: release

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          make setup
          uv pip install twine

      - name: Build the package
        run: uv build --link-mode copy

      - name: List dist directory
        run: ls -l dist/

      - name: Check distribution's long description rendering on PyPI
        run: uv run twine check dist/*

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
